package com.itheima.dao.feedback;

import com.itheima.domain.feedback.Feedback;
import com.itheima.domain.feedback.FeedbackExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.web.bind.annotation.RequestParam;

import java.util.List;

public interface FeedbackDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback_c
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String feedbackId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback_c
     *
     * @mbg.generated
     */
    int insert(Feedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback_c
     *
     * @mbg.generated
     */
    int insertSelective(Feedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback_c
     *
     * @mbg.generated
     */
    List<Feedback> selectByExample(FeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback_c
     *
     * @mbg.generated
     */
    Feedback selectByPrimaryKey(String feedbackId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback_c
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Feedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback_c
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Feedback record);

    List<Feedback> findByUserId(@Param("userId") String userId,@Param("isShare") String isShare);

    Integer findByNewFeedback(String state);

    List<Feedback> findByToday(@Param("today") String today, @Param("state") String state);
}