package com.itheima.domain.feedback;

import java.io.Serializable;
import java.util.Date;

public class Feedback implements Serializable {

    @Override
    public String toString() {
        return "Feedback{" +
                "feedbackId='" + feedbackId + '\'' +
                ", inputBy='" + inputBy + '\'' +
                ", inputTime=" + inputTime +
                ", title='" + title + '\'' +
                ", content='" + content + '\'' +
                ", classType='" + classType + '\'' +
                ", tel='" + tel + '\'' +
                ", answerBy='" + answerBy + '\'' +
                ", answerTime=" + answerTime +
                ", solveMethod='" + solveMethod + '\'' +
                ", resolution='" + resolution + '\'' +
                ", difficulty='" + difficulty + '\'' +
                ", isShare='" + isShare + '\'' +
                ", state='" + state + '\'' +
                ", createBy='" + createBy + '\'' +
                ", createDept='" + createDept + '\'' +
                ", createTime=" + createTime +
                '}';
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback_c.FEEDBACK_ID
     *
     * @mbg.generated
     */
    private String feedbackId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback_c.INPUT_BY
     *
     * @mbg.generated
     */
    private String inputBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback_c.INPUT_TIME
     *
     * @mbg.generated
     */
    private Date inputTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback_c.TITLE
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback_c.CONTENT
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback_c.CLASS_TYPE
     *
     * @mbg.generated
     */
    private String classType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback_c.TEL
     *
     * @mbg.generated
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback_c.ANSWER_BY
     *
     * @mbg.generated
     */
    private String answerBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback_c.ANSWER_TIME
     *
     * @mbg.generated
     */
    private Date answerTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback_c.SOLVE_METHOD
     *
     * @mbg.generated
     */
    private String solveMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback_c.RESOLUTION
     *
     * @mbg.generated
     */
    private String resolution;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback_c.DIFFICULTY
     *
     * @mbg.generated
     */
    private String difficulty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback_c.IS_SHARE
     *
     * @mbg.generated
     */
    private String isShare;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback_c.STATE
     *
     * @mbg.generated
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback_c.CREATE_BY
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback_c.CREATE_DEPT
     *
     * @mbg.generated
     */
    private String createDept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback_c.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback_c.FEEDBACK_ID
     *
     * @return the value of feedback_c.FEEDBACK_ID
     *
     * @mbg.generated
     */
    public String getFeedbackId() {
        return feedbackId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback_c.FEEDBACK_ID
     *
     * @param feedbackId the value for feedback_c.FEEDBACK_ID
     *
     * @mbg.generated
     */
    public void setFeedbackId(String feedbackId) {
        this.feedbackId = feedbackId == null ? null : feedbackId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback_c.INPUT_BY
     *
     * @return the value of feedback_c.INPUT_BY
     *
     * @mbg.generated
     */
    public String getInputBy() {
        return inputBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback_c.INPUT_BY
     *
     * @param inputBy the value for feedback_c.INPUT_BY
     *
     * @mbg.generated
     */
    public void setInputBy(String inputBy) {
        this.inputBy = inputBy == null ? null : inputBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback_c.INPUT_TIME
     *
     * @return the value of feedback_c.INPUT_TIME
     *
     * @mbg.generated
     */
    public Date getInputTime() {
        return inputTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback_c.INPUT_TIME
     *
     * @param inputTime the value for feedback_c.INPUT_TIME
     *
     * @mbg.generated
     */
    public void setInputTime(Date inputTime) {
        this.inputTime = inputTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback_c.TITLE
     *
     * @return the value of feedback_c.TITLE
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback_c.TITLE
     *
     * @param title the value for feedback_c.TITLE
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback_c.CONTENT
     *
     * @return the value of feedback_c.CONTENT
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback_c.CONTENT
     *
     * @param content the value for feedback_c.CONTENT
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback_c.CLASS_TYPE
     *
     * @return the value of feedback_c.CLASS_TYPE
     *
     * @mbg.generated
     */
    public String getClassType() {
        return classType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback_c.CLASS_TYPE
     *
     * @param classType the value for feedback_c.CLASS_TYPE
     *
     * @mbg.generated
     */
    public void setClassType(String classType) {
        this.classType = classType == null ? null : classType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback_c.TEL
     *
     * @return the value of feedback_c.TEL
     *
     * @mbg.generated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback_c.TEL
     *
     * @param tel the value for feedback_c.TEL
     *
     * @mbg.generated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback_c.ANSWER_BY
     *
     * @return the value of feedback_c.ANSWER_BY
     *
     * @mbg.generated
     */
    public String getAnswerBy() {
        return answerBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback_c.ANSWER_BY
     *
     * @param answerBy the value for feedback_c.ANSWER_BY
     *
     * @mbg.generated
     */
    public void setAnswerBy(String answerBy) {
        this.answerBy = answerBy == null ? null : answerBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback_c.ANSWER_TIME
     *
     * @return the value of feedback_c.ANSWER_TIME
     *
     * @mbg.generated
     */
    public Date getAnswerTime() {
        return answerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback_c.ANSWER_TIME
     *
     * @param answerTime the value for feedback_c.ANSWER_TIME
     *
     * @mbg.generated
     */
    public void setAnswerTime(Date answerTime) {
        this.answerTime = answerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback_c.SOLVE_METHOD
     *
     * @return the value of feedback_c.SOLVE_METHOD
     *
     * @mbg.generated
     */
    public String getSolveMethod() {
        return solveMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback_c.SOLVE_METHOD
     *
     * @param solveMethod the value for feedback_c.SOLVE_METHOD
     *
     * @mbg.generated
     */
    public void setSolveMethod(String solveMethod) {
        this.solveMethod = solveMethod == null ? null : solveMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback_c.RESOLUTION
     *
     * @return the value of feedback_c.RESOLUTION
     *
     * @mbg.generated
     */
    public String getResolution() {
        return resolution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback_c.RESOLUTION
     *
     * @param resolution the value for feedback_c.RESOLUTION
     *
     * @mbg.generated
     */
    public void setResolution(String resolution) {
        this.resolution = resolution == null ? null : resolution.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback_c.DIFFICULTY
     *
     * @return the value of feedback_c.DIFFICULTY
     *
     * @mbg.generated
     */
    public String getDifficulty() {
        return difficulty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback_c.DIFFICULTY
     *
     * @param difficulty the value for feedback_c.DIFFICULTY
     *
     * @mbg.generated
     */
    public void setDifficulty(String difficulty) {
        this.difficulty = difficulty == null ? null : difficulty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback_c.IS_SHARE
     *
     * @return the value of feedback_c.IS_SHARE
     *
     * @mbg.generated
     */
    public String getIsShare() {
        return isShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback_c.IS_SHARE
     *
     * @param isShare the value for feedback_c.IS_SHARE
     *
     * @mbg.generated
     */
    public void setIsShare(String isShare) {
        this.isShare = isShare == null ? null : isShare.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback_c.STATE
     *
     * @return the value of feedback_c.STATE
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback_c.STATE
     *
     * @param state the value for feedback_c.STATE
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback_c.CREATE_BY
     *
     * @return the value of feedback_c.CREATE_BY
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback_c.CREATE_BY
     *
     * @param createBy the value for feedback_c.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback_c.CREATE_DEPT
     *
     * @return the value of feedback_c.CREATE_DEPT
     *
     * @mbg.generated
     */
    public String getCreateDept() {
        return createDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback_c.CREATE_DEPT
     *
     * @param createDept the value for feedback_c.CREATE_DEPT
     *
     * @mbg.generated
     */
    public void setCreateDept(String createDept) {
        this.createDept = createDept == null ? null : createDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback_c.CREATE_TIME
     *
     * @return the value of feedback_c.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback_c.CREATE_TIME
     *
     * @param createTime the value for feedback_c.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}